server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API 프록시 설정 (필요 시)
    location /api/ {
        proxy_pass http://back:8000/;
    }
}