FROM python:3.13.11
RUN apt-get update
RUN apt-get upgrade -y
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN pip install uv

WORKDIR /workspace

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY main.py main.py

EXPOSE 8000

CMD ["uv", "run", "fastapi", "run", "--host", "0.0.0.0", "--port", "8000"]