apiVersion: v1
kind: Pod

metadata:
  name: maria

spec:
  containers:
    - name: maria
      image: mariadb:12.1.2
      ports:
        - containerPort: 3306
      env:
        - name: MARIADB_ROOT_PASSWORD
          value: passwd
        - name: MARIADB_DATABASE
          value: edu
