FROM ubuntu:22.04
RUN apt-get update
RUN apt-get -y install wget ssh curl openjdk-21-jdk python3-pip procps net-tools
RUN pip3 install jupyter pyspark pandas

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

WORKDIR /opt

EXPOSE 8888

CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--allow-root", "--ip=0.0.0.0"]