name: "🐞Bug"
description: "버그 리포트 템플릿"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: 🐞버그 설명
      description: 어떤 상황에서 어떤 문제가 발생했는지 구체적으로 작성해주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🐛에러 로그
      description: 콘솔에 찍힌 에러 로그나 네트워크 응답 에러가 있다면 코드 블럭에 포함해주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅작업할 내용
      description: 버그를 해결하기 위해 예상되는 작업을 세분화해서 체크박스 형태로 작성해주세요.
  - type: textarea
    attributes:
      label: 📸스크린샷
      description: 시각적으로 이해를 돕기 위한 스크린샷이 있다면 첨부해주세요.
  - type: textarea
    attributes:
      label: 📑참고 문서
      description: 참고할 수 있는 자료가 있다면 업로드 해주세요.