# mountPath의 파일을 변경하면 바로바로 적용됨, 변경사항이 많은 파일에 사용하는게 좋음

apiVersion: v1
kind: Pod
metadata:
  name: local-disk-pod
  labels:
    app: nginx

spec:
  containers:
    - name: nginx-container
      image: nginx:1.28
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: local-vol

  volumes:
  - name: local-vol
    persistentVolumeClaim:
      claimName: local-pvc



---


apiVersion: v1
kind: Service

metadata:
  name: vol-service
    
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx