apiVersion: v1
kind: Pod

metadata:
  name: local-disk-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:1.28
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: local-vol
  volumes:
    - name: local-vol
    # hostPath = 내 로컬 PC위치의 disk를 Pod의 disk에 연결시켜주는 연결
      hostPath:
      # 리눅스 형식으로 써줘야함 (/run/desktop/mnt/host/c/ = C:)
        path: /run/desktop/mnt/host/c/Users/hi/Desktop/수아/수아짱짱맨뿡뿡/fullstack-journey/practice_file/0226/html
        type: DirectoryOrCreate

--- 

apiVersion: v1
kind: Service

metadata:
  name: vol-service

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
