version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - app-network
    restart: always

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "6100:8000"
    depends_on:
      - ollama
    networks:
      - app-network
    restart: always

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data:
