FROM python:3.12.9

RUN apt-get update
RUN apt-get upgrade -y
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN pip install uv

WORKDIR /workspace

COPY ./pyproject.toml ./uv.lock ./

RUN uv sync --frozen --no-dev

COPY ./.env ./.env
COPY . .

EXPOSE 8000